language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t georgilv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true georgilv/react-test npm test -- --coverage

after_success:
  - docker build -t georgilv/multi-client ./client
  - docker build -t georgilv/multi-nginx ./nginx
  - docker build -t georgilv/multi-server ./server
  - docker build -t georgilv/multi-worker ./worker
