language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t georgilv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true georgilv/react-test npm test -- --coverage

after_success:
  - docker build -t georgilv/multi-client ./client
  - docker build -t georgilv/multi-nginx ./nginx
  - docker build -t georgilv/multi-server ./server
  - docker build -t georgilv/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push georgilv/multi-client
  - docker push georgilv/multi-nginx
  - docker push georgilv/multi-server
  - docker push georgilv/multi-worker
