sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t georglv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true georglv/react-test npm test

after_success:
  - docker build -t georglv/multi-client ./client
  - docker build -t georglv/multi-nginx ./nginx
  - docker build -t georglv/multi-server ./server
  - docker build -t georglv/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push georglv/multi-client
  - docker push georglv/multi-nginx
  - docker push georglv/multi-server
  - docker push georglv/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'multi-docker-bucket2'
  bucket_path: 'multi-docker-bucket2'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

